version: "3"

services:
  lancer:
    image: lancer:latest
    container_name: lancer
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"

  redis:
    image: redis:7.2.3-alpine
    container_name: redis-lancer
    ports:
      - "6379:6379"
    command: redis-server --requirepass lancer123


  mysql:
    image: mariadb
    container_name: mariadb-lancer
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: lancer123456
      MYSQL_DATABASE: lancer
      MYSQL_USER: lancer
      MYSQL_PASSWORD: lancer123
    volumes:
      - ./mysql_data:/var/lib/mysql


 # user:default password:''
  clickhouse:
    container_name: clickhouse-lancer
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse